version: "3"

services:
  mongoDB:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    restart: always
  webapp:
    depends_on:
      - mongoDB
    build: .
    ports:
      - 80:8000
    restart: always
    environment:
      - MONGO_DB_URL=mongodb://mongoDB:27017/nasa
  worker:
    command: ["node", "worker.js"]
    depends_on:
      - mongoDB
    build: .
    restart: always
    environment:
      - MONGO_DB_URL=mongodb://mongoDB:27017/nasa

volumes:
  mongo_data:
